#!/usr/bin/env bash

if [ $# -lt 2 ]; then
    echo "Usage: $0 <input.apk> <output_dir>"
    exit
fi


input=$1
output=$2
if [ -d "$output" ]; then
    echo "Output directory already exists, please choose a non-existing directory, it will be created by the tool."
    exit 1
fi

dir="$(dirname -- "$(readlink -f -- "$BASH_SOURCE")")"

function decompile() {
    echo "Decompiling..."
    java -jar "$dir/deps/jadx.jar" -d decompiled *.dex
}

function apktool() {
    echo "Apktool $input"
    java -jar "$dir/deps/apktool.jar" d "$input" -o "$output" -f -s
}

apktool
cd "$output"
decompile
